version: "3.9"
services:
    django-db:
        image: mysql:5.7
        ports:
            - "3306:3306"
        environment:
            - MYSQL_DATABASE=${FBOOKING_DB_NAME}
            - MYSQL_USER=${FBOOKING_DB_USER}
            - MYSQL_PASSWORD=${FBOOKING_DB_PASSWORD}
            - MYSQL_RANDOM_ROOT_PASSWORD=1
        volumes:
            - ../mysql-volume:/var/lib/mysql